### ISSUE TITLE
Use Creative Commons instead of GPL?

### ISSUE THREAD

**Issue by tamberg** [CasaJasmina/letters#2]
Hi, as letters are creative work rather than software, could it make sense to use a Creative Commons License (https://creativecommons.org/choose/) instead of GPL? E.g. CC BY-SA-NC. Kind regards, Thomas

**Comment by thornet** [comment]
@tamberg, thanks for the note! I definitely agree. I had looked for CC BY-SA when uploading the letters, but it wasn't an option in Github. Will investigate.

**Comment by thornet** [comment]
Changed to CC BY-SA 4.0. Thanks, @tamberg!

**Comment by tamberg** [comment]
Thanks!
